import { expect, test } from '@playwright/test'

test.describe('experience and principle research workbench', () => {
  test('shows verified sources and changes forecast horizon using real results', async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/knowledge')
    await expect(page.getByLabel('知识库概况')).toContainText('140')
    await page.getByRole('tab', { name: '回测证据', exact: true }).click()
    const table = page.getByRole('region', { name: '模型误差对照表' })
    await expect(table).toContainText('5.90%')
    await expect(table).toContainText('5.80%')
    await page.getByRole('button', { name: '未来 4 日', exact: true }).click()
    await expect(table).toContainText('6.85%')
    await expect(table).toContainText('6.67%')
    await expect(page.getByText('725', { exact: false }).first()).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    expect(errors).toEqual([])
  })

  test('saves a manual experience, edits append-only history, and keeps old versions after reload', async ({ page }) => {
    await page.goto('/knowledge')
    await page.getByRole('button', { name: '新增记录', exact: true }).click()
    const dialog = page.getByRole('dialog')
    await dialog.locator('#kw-entry-title').fill('测试：回撤观察')
    await dialog.locator('#kw-entry-text').fill('接近五日线时先记录，不把触达当作成交。')
    await dialog.locator('summary').click()
    await dialog.locator('#kw-entry-interpretation').fill('用于观察MA5附近的价格行为，尚待定义。')
    await dialog.getByRole('button', { name: '保存记录', exact: true }).click()
    const details = page.getByRole('region', { name: '记录详情' })
    await expect(details).toContainText('测试：回撤观察')
    await details.getByRole('button', { name: '编辑记录', exact: true }).click()
    await page.getByRole('dialog').locator('#kw-entry-interpretation').fill('第二版：区分触达、收盘站稳和失效条件。')
    await page.getByRole('button', { name: '保存新版本', exact: true }).click()
    await expect(details).toContainText('第二版：区分触达')
    await details.locator('summary').filter({ hasText: '版本历史' }).click()
    await details.getByRole('button', { name: '查看 v1', exact: true }).click()
    await expect(details).toContainText('历史版本，只读')
    await expect(details).toContainText('用于观察MA5附近的价格行为')
    await page.reload()
    await page.getByRole('textbox', { name: '搜索经验记录' }).fill('测试：回撤观察')
    await page.getByRole('button', { name: '查看记录：测试：回撤观察', exact: true }).click()
    await expect(details).toContainText('第二版：区分触达')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  })

  test('preserves the user three-day reference interpretation and exposes original note citations', async ({ page }) => {
    await page.goto('/knowledge')
    await page.getByRole('textbox', { name: '搜索经验记录' }).fill('三天 MA5')
    await page.getByRole('button', { name: /查看记录：三天 MA5/ }).click()
    await expect(page.getByRole('region', { name: '记录详情' })).toContainText('不解释为连续三日站上均线')
    await page.getByRole('textbox', { name: '搜索经验记录' }).fill('增量外推参数')
    await page.getByRole('button', { name: '查看记录：MA5 / BOLL 增量外推参数', exact: true }).click()
    await expect(page.getByRole('region', { name: '记录详情' })).toContainText('MA5')
    await expect(page.getByRole('region', { name: '记录详情' }).locator('a[href*="707f4fe"]').first()).toBeAttached()
    const original = await page.getByRole('region', { name: '记录详情' }).locator('.kw-original').textContent()
    await page.getByRole('button', { name: '修正解释', exact: true }).click()
    const edit = page.getByRole('dialog', { name: '修正 AI 解释' })
    await expect(edit.locator('#kw-entry-text')).toHaveAttribute('readonly', '')
    const sourceText = await edit.locator('#kw-entry-text').inputValue()
    await edit.getByLabel('修正后的解释').fill('修正测试：仅使用当时已知均线外推，不读取未来指标。')
    await edit.getByRole('button', { name: '保存新版本', exact: true }).click()
    await expect(page.getByRole('region', { name: '记录详情' })).toContainText('修正测试：仅使用当时已知均线外推')
    await expect(page.getByRole('region', { name: '记录详情' })).toContainText('当前版本需重新检验')
    expect(sourceText).toBe(original)
    await expect(page.getByRole('region', { name: '记录详情' }).locator('.kw-original')).toHaveText(original!)
  })
})
